baseURL: "https://www.example.com/"
theme: "up-business-theme"
languageCode: "en-us"

title: "inPyjama!"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "inPyjama!"
  description: "Everything is simple if you know how to look at it!"
  images:
    - "images/hero-image.png"

  logo: "logo.png"

  favicons:
    themeColor: "#f85f73"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    dribbble: "#"

  location:
    - "Keerthi Harmony, Raghevendra Circle, Bangalore - 560016"

  contact:
    - "support@inpyjama.com"
    - "business@inpyjama.com"
    - "+91-8197611671"

  copyright: "© 2024 Typobrahe Education LLP. All Rights Reserved."

menus:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Blog"
      url: "https://blog.inpyjama.com"
      weight: 2
    - name: "YouTube"
      url: ""
      weight: 3
    - name: "Discord"
      url: ""
      weight: 4
    - name: "Whatsapp"
      url: ""
      weight: 5
    - name: "Courses"
      url: "https://engineers.inpyjama.com/learn"
      weight: 6

  buttons:
    - name: "Course Login"
      url: "https://engineers.inpyjama.com/learn/account/signin"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "Blog"
      url: "/blog"
      weight: 2

    - name: "Our team"
      url: "/#"
      weight: 3

    - name: "Pricing"
      url: "/#"
      weight: 4

    - name: "Blog"
      url: "/"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"
